# playbooks/patch_report.yml
- name: Collect pending patches
  hosts: all
  become: true
  gather_facts: true
  roles:
    - patch_scan

- name: Generate reports (controller)
  hosts: localhost
  gather_facts: false
  roles:
    - report_generate
    - mail_send
