[ubuntu]

ubuntu1 ansible_host=192.168.2.6 ansible_user=ubuntu

[windows]
192.168.0.104

[windows:vars]
ansible_user=Administrator
ansible_password=Sameer@19
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_scheme=http
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
ansible_winrm_operation_timeout_sec=120
ansible_winrm_read_timeout_sec=180
