---
- name: Generate SSL certificates
  include_tasks: "{{ ssl_certificate_type }}.yml"
  when: ssl_certificate_type in ['self_signed', 'letsencrypt']

- name: Set certificate permissions
  file:
    path: "{{ ssl_private_key_path }}/{{ ssl_domain }}.key"
    owner: root
    group: "{{ nginx_user }}"
    mode: "0640"
  notify:
    - Reload Nginx
