- name: RHEL Patch and Reboot
  hosts: rhel
  gather_facts: true
  become: true
  roles:
    - patching
    - reboot

- name: Generate and Send Patch Report
  hosts: localhost
  gather_facts: true
  become: false
  roles:
    - reporting
