---
- name: Update Ubuntu Server Patches
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Remove unused packages
      apt:
        autoremove: yes
        purge: yes

    - name: Clean apt cache
      apt:
        autoclean: yes 