---
- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewalld zones
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    immediate: yes

- name: Allow services in firewalld
  firewalld:
    service: "{{ item }}"
    zone: public
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - ssh
    - http
    - https
