# SMTP settings
smtp_host: smtp.gmail.com
smtp_port: 587
smtp_secure: starttls

# Gmail auth
gmail_username: computecentral.in@gmail.com

# Mail headers
mail_from: computecentral.in@gmail.com
mail_to: sameeralam358@gmail.com
