- name: Ensure remote report directory exists
  file:
    path: "{{ patch_report_path }}"
    state: directory
    mode: '0755'

- name: Check for available updates based on OS
  shell: |
    {% if ansible_os_family == 'RedHat' %}
    dnf check-update || true
    {% elif ansible_os_family == 'Debian' %}
    apt list --upgradeable || true
    {% elif ansible_os_family == 'Suse' %}
    zypper list-updates || true
    {% else %}
    echo "Unsupported OS"
    {% endif %}
  register: patch_output
  changed_when: false

- name: Save formatted patch report to file on remote host
  template:
    src: patch_report.j2
    dest: "{{ patch_report_path }}/{{ inventory_hostname }}_patch_report.txt"

- name: Apply updates based on OS
  block:
    - name: Apply updates on RHEL
      dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Apply updates on Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Apply updates on SUSE
      zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"
  become: true

- name: Fetch patch report from remote host to control machine
  fetch:
    src: "{{ patch_report_path }}/{{ inventory_hostname }}_patch_report.txt"
    dest: "./reports/"
    flat: yes
