---
- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_flag

- name: Reboot system if required
  ansible.builtin.reboot:
    reboot_timeout: "{{ reboot_timeout }}"
    test_command: "{{ reboot_test_command }}"
  when: reboot_flag.stat.exists
